2021-03-12 17:11:59,646, DEBUG, __name__, Запуск бота
2021-03-12 17:11:59,646, DEBUG, __name__, Запуск бота
2021-03-12 17:11:59,910, DEBUG, __name__, Запуск бота
2021-03-12 17:11:59,910, INFO, __name__, Бот отправляет сообщение
2021-03-12 17:11:59,911, DEBUG, telegram.bot, Entering: send_message
2021-03-12 17:11:59,911, DEBUG, telegram.vendor.ptb_urllib3.urllib3.connectionpool, Starting new HTTPS connection (1): api.telegram.org
2021-03-12 17:12:00,224, DEBUG, telegram.vendor.ptb_urllib3.urllib3.connectionpool, https://api.telegram.org:443 "POST /bot1650807367:AAFeaTkMe8F7A79lyyshrUdHnjZ4ueP-NXw/sendMessage HTTP/1.1" 200 616
2021-03-12 17:12:00,225, DEBUG, telegram.bot, {'message_id': 74, 'date': 1615558321, 'chat': {'id': 326793701, 'type': 'private', 'first_name': 'Тимур', 'last_name': 'А.'}, 'text': 'У вас проверили работу "TimurAtambaev__api_sp1_bot.zip"!\n\nК сожалению в работе нашлись ошибки.', 'entities': [], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1650807367, 'first_name': 'telegram_bot', 'is_bot': True, 'username': 'kind_maverick_bot'}}
2021-03-12 17:12:00,225, DEBUG, telegram.bot, Exiting: send_message
